version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
    restart: unless-stopped
    environment:
      - BACKEND_CORS_ORIGINS=https://dify-plugin.resline.net
      - TEMP_DIR=/app/temp
      - SCRIPTS_DIR=/app/scripts
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-10}
      - FILE_RETENTION_HOURS=${FILE_RETENTION_HOURS:-24}
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - PYTHONPATH=/app/backend
    volumes:
      - temp-data:/app/temp
      - redis-data:/var/lib/redis
    expose:
      - "80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health && cd /app/backend && celery -A app.workers.celery_app inspect ping --timeout=10 | grep -q OK && redis-cli ping | grep -q PONG"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s

volumes:
  temp-data:
  redis-data: